# GoonCraft Configuration
# =======================
# Customize all plugin messages here!
# Use color codes with § or & (e.g., &6 for gold, &c for red)
# Available placeholders: {player}, {target}, {value}, {min}, {max}

messages:
  # General
  only-players: "&cOnly players can use this command"
  player-not-found: "&cPlayer not found"
  no-permission: "&cYou don't have permission to do that"
  no-stats: "&cNo stats found"

  # Penis commands
  penis:
    usage: "&6Usage: /penis <size|girth|bbc|toggle> [player]"
    unknown-subcommand: "&cUnknown subcommand. Use: size, girth, bbc, or toggle"
    
    # Size
    your-size: "&6Your penis size is &e{value}cm"
    player-size: "&6{player}'s penis size is &e{value}cm"
    size-set: "&aSet {player}'s penis size to {value}cm"
    size-range: "&cSize must be between {min} and {max}cm"
    
    # Girth
    your-girth: "&6Your penis girth is &e{value}cm"
    player-girth: "&6{player}'s penis girth is &e{value}cm"
    girth-set: "&aSet {player}'s penis girth to {value}cm"
    girth-range: "&cGirth must be between {min} and {max}cm"
    
    # BBC
    you-have-bbc: "&aYes, you have a BBC"
    you-no-bbc: "&cNo, you don't have a BBC"
    player-has-bbc: "&a{player} has a BBC"
    player-no-bbc: "&c{player} doesn't have a BBC"
    bbc-set-true: "&aSet {player}'s penis to a BBC"
    bbc-set-false: "&aSet {player}'s penis to a regular penis"
    invalid-boolean: "&cValue must be true or false"
    
    # Toggle
    need-penis: "&cYou need to have a penis to use this command"
    no-penis: "&cYou don't have a penis! Use &e/gender change &cto get one."
    whipped-out: "&aYou whipped it out!"
    put-away: "&aYou put it away."

  # Buttfinger command
  buttfinger:
    usage: "&cUsage: /buttfinger <player>"
    cooldown: "&cYou can only buttfinger once every {value} seconds"
    too-far: "&cPlayer is too far away to buttfinger!"
    self: "&6You just buttfinger'd yourself! Kinky..."
    victim: "&6You have been buttfinger'd by &e{player}&6!"
    success: "&aYou buttfinger'd &e{target}&a!"

  # Viagra
  viagra:
    need-toggle: "&cYou need to have your dick out to use this Viagra!"
    success: "&aNice cock bro! Your dick temporarily grew {value}cm!"
    given: "&aYou've been given a Viagra pill!"

  # Cum messages
  cum:
    fap: "&7Fap..."
    ejaculate: "&7Hmmfff.. *ejaculates*"
    cummed-on: "&6You have been cummed on by &a&l{player}"

  # Gender messages
  gender:
    current: "&7Your current gender is: {gender}"
    change-hint: "&7Use &e/gender change &7to change it"
    selected-male: "&bYou selected Male! &7You have been given a penis."
    selected-female: "&dYou selected Female! &7You have been given boobs."
    selected-other: "&c&lO&6&lt&e&lh&a&le&b&lr&d&l! &7You have been given BOTH!"

  # Boobs messages
  boobs:
    usage: "&6Usage: /boobs <size|perkiness|toggle|jiggle>"
    unknown-subcommand: "&cUnknown subcommand. Use: size, perkiness, toggle, or jiggle"
    no-boobs: "&cYou don't have boobs! Use &e/gender change &cto get some."
    your-size: "&dYour boob size is &e{value}"
    player-size: "&d{player}'s boob size is &e{value}"
    player-no-boobs: "&c{player} doesn't have boobs!"
    size-set: "&aSet {player}'s boob size to {value}"
    size-range: "&cSize must be between {min} and {max}"
    your-perkiness: "&dYour boob perkiness is &e{value}"
    player-perkiness: "&d{player}'s boob perkiness is &e{value}"
    perkiness-set: "&aSet {player}'s boob perkiness to {value}"
    perkiness-range: "&cPerkiness must be between {min} and {max}"
    whipped-out: "&dYou flashed your boobs!"
    put-away: "&dYou covered up."
    need-toggle: "&cYou need to have your boobs out first! Use &e/boobs toggle"
    jiggle: "&d*jiggle jiggle*"

  # Bodily function messages
  bodily:
    cooldown: "&cYou need to wait before doing that again!"
    piss-need-toggle: "&cYou need to have your penis out to piss!"
    fart: "&e{player} &7let one rip... &8*pffrrrt*"
    poop: "&6{player} &7just dropped a deuce... &8*plop*"
    piss: "&e{player} &7is taking a leak..."

  # Statistics
  stats:
    header: "&6&l═══ {player}'s Goon Stats ═══"
    fap-count: "&7Faps: &e{value}"
    cum-on-others: "&7Cummed on others: &e{value}"
    got-cummed-on: "&7Got cummed on: &e{value}"
    time-with-penis-out: "&7Time with penis out: &e{value}"
    buttfingers-given: "&7Buttfingers given: &e{value}"
    buttfingers-received: "&7Buttfingers received: &e{value}"
    viagra-used: "&7Viagra used: &e{value}"
    achievements: "&6Achievements: &e{unlocked}&7/&e{total}"

  # Achievements
  achievement:
    unlocked-title: "&6&l★ ACHIEVEMENT UNLOCKED ★"
    unlocked-name: "&e{name}"
    unlocked-description: "&7{description}"
    broadcast: "&6{player} &7unlocked the achievement &e{name}&7!"

  achievements:
    header: "&6&l═══ {player}'s Achievements ({unlocked}/{total}) ═══"

  # Leaderboard
  leaderboard:
    header: "&6&l═══ Leaderboard: {category} ═══"

# Viagra item settings
viagra:
  boost-amount: 5
  item-name: "&dViagra"
  item-lore:
    - "&aCan't get it up or simply have a small ween?"
    - "&aTake this for a temporary +{value}cm boost!"

# Cooldowns (in seconds)
cooldowns:
  buttfinger: 5

# Chat message settings
chat:
  # Show "Fap..." messages to nearby players
  show-fap-messages: true
  # Show "*ejaculates*" messages to nearby players
  show-ejaculate-messages: true
  # Show "You have been cummed on" messages
  show-cummed-on-messages: true
  # Show fart messages to nearby players
  show-fart-messages: true
  # Show poop messages to nearby players
  show-poop-messages: true
  # Show piss messages to nearby players
  show-piss-messages: true
